type DetailedTeam {
    id: Int
    abbreviation: String
    name: String
    active: Boolean
    venue: Venue
    rosterResponse: [Player]
    goalies: [Player]
    defenders: [Player]
    forwards: [Player]
  }