query articles($query: String){
    articles(query: $query) { 
      title,
      content,
      description,
      publishedAt,
      url,
      author,
      urlToImage,
      source { 
        name 
      }
    }
  }