query teamLocations {
    teamLocations {
      teamLocations {
        id
        text
        center
        color
      }
      seasonDescription
      divisions {
        key
        value
      }
    }
  }