query searchPlayerByName($name: String) {
    searchPlayerByName(name: $name) {
      id
      fullName
      primaryPosition {
        code
        name
        type
      }
      currentTeam {
        id
        name
      }
    }
  }