  query playerDetailedStats($id: Int, $seasonId: String) {
    playerDetailedStats(id: $id, seasonId: $seasonId) {
      byMonth {
        season
        stat {
          ...GoalieStatsFragment
        }
        month
      }
      gameLog {
        season
        stat {
          ...GoalieStatsFragment
        }
        team {
          id
          name
        }
        opponent {
          id
          name
        }
        isHome
        isOT
        isWin
        date
        game {
          gamePk
        }
      }
    }
  }