type Player {
    id: Int
    description: String
    fullName: String
    currentAge: Int
    jerseyNumber: Int
    active: Boolean
    alternateCaptain: Boolean
    birthCity: String
    birthDate: String
    captain: Boolean
    currentTeam: Team
    firstName: String
    lastName: String
    height: Int
    primaryNumber: Int
    primaryPosition: Position
    rookie: Boolean
    rosterStatus: String
    shootsCatches: String
    weight: Int
    nationality: String
    capHit: String
    stats: Stats
    nhlStats: StatsCollection
    careerStats: StatsCollection
}

type StatsCollection {
  totalGames: Int
  totalGoals: Int
  totalAssists: Int
  totalPoints: Int
  totalGamesStarted: Int
  totalWins: Int
  gamesLine: [LineInt]
  gamesStartedLine: [LineInt]
  winsLine: [LineInt]
  goalsLine: [LineInt]
  assistsLine: [LineInt]
  stats: [SeasonStats]
}

type SeasonStats {
  season: String
  team: Team
  league: League
  stat: Stats
}

type Stats {
  games: Int
  timeOnIce: String
  # skater props
  goals: Int
  assists: Int
  points: Int
  pim: Int
  penaltyMinutes: Int
  plusMinus: Int
  shots: Int
  hits: Int
  blocked: Int
  faceOffPct: String
  faceOffWins: Int
  faceoffTaken: Int
  evenTimeOnIce: String
  evenTimeOnIceMinutes: Int
  powerPlayTimeOnIce: String
  powerPlayTimeOnIceMinutes: Int
  shotPct: String
  gameWinningGoals: Int
  powerPlayGoals: Int
  powerPlayAssists: Int
  powerPlayPoints: Int
  shortHandedGoals: Int
  shortHandedAssists: Int
  shortHandedPoints: Int
  shortHandedTimeOnIce: String
  shortHandedTimeOnIceMinutes: Int
  # goalie props
  gamesStarted: Int
  goalAgainstAverage: Float
  savePercentage: Float
  wins: Int
  losses: Int
  ot: Int
  saves: Int
  evenSaves: Int
  powerPlaySaves: Int
  shortHandedSaves: Int
  shotsAgainst: Int
  evenShots: Int
  powerPlayShots: Int
  shortHandedShots: Int
  evenStrengthSavePercentage: Float
  powerPlaySavePercentage: Float
  shortHandedSavePercentage: Float
  shutouts: Int
}

type League {
  id: Int
  name: String
}

type Position {
    code: String
    name: String
    type: String
    abbreviation: String
}

type SelectedPlayers {
  skaters: [Player]
  goalies: [Player]
}