#import "../fragments/skaterStatsFragment.gql"

  query game($gameId: Int) {
    game(gameId: $gameId) {
      id
      gameDate
      gameType
      percentage
      venue {
        id
        name
      }
      season
      teams {
        home {
          skaters {
            jerseyNumber
            person {
              id
              fullName
            }
            position {
              code
              name
            }
            stats {
              ...SkaterStatsFragment
            }
          }
          goalies {
            jerseyNumber
            person {
              id
              fullName
            }
            position {
              code
              name
            }
            stats {
              timeOnIce
              shots
              saves
              savePercentage
              powerPlaySaves
              shortHandedSaves
              evenSaves
              shortHandedShotsAgainst
              evenShotsAgainst
              savePercentage
              powerPlaySavePercentage
              shortHandedSavePercentage
              evenStrengthSavePercentage
            }
          }
          team {
            id
            name
          }
          coaches {
            person {
              fullName
            }
            position {
              code
              name
              type
            }
          }
        }
        away {
          skaters {
            jerseyNumber
            person {
              id
              fullName
            }
            position {
              code
              name
            }
            stats {
              ...SkaterStatsFragment
            }
          }
          goalies {
            jerseyNumber
            person {
              id
              fullName
            }
            position {
              code
              name
            }
            stats {
              timeOnIce
              shots
              saves
              savePercentage
              powerPlaySaves
              shortHandedSaves
              evenSaves
              shortHandedShotsAgainst
              evenShotsAgainst
              savePercentage
              powerPlaySavePercentage
              shortHandedSavePercentage
              evenStrengthSavePercentage
            }
          }
          team {
            id
            name
          }
          coaches {
            person {
              fullName
            }
            position {
              code
              name
              type
            }
          }
        }
      }
      officials {
        official {
          id
          fullName
        }
        officialType
      }
      linescore {
        currentPeriodOrdinal
        currentPeriodTimeRemaining
        teams {
          home {
            goals
            shotsOnGoal
          }
          away {
            goals
            shotsOnGoal
          }
        }
        periods {
          num
          home {
            goals
            shotsOnGoal
          }
          away {
            goals
            shotsOnGoal
          }
        }
      }
    }
  }