export const GET_SCHEDULE = 'GET_SCHEDULE';
export const SCHEDULE_LOADED = 'SCHEDULE_LOADED';
export const GET_TEAM_SCHEDULE = 'GET_TEAM_SCHEDULE';
export const TEAM_SCHEDULE_LOADED = 'TEAM_SCHEDULE_LOADED';
export const GET_STANDINGS = 'GET_STANDINGS';
export const STANDINGS_LOADED = 'STANDINGS_LOADED';